apiVersion: keip.octo.com/v1alpha1
kind: IntegrationRoute
metadata:
  name: testroute
spec:
  replicas: 1
  routeConfigMap: testroute-xml
  propSources:
    - name: testroute-props
    # Can also select ConfigMaps using labels:
    # - labels:
    #     group: abc
  secretSources:
    - testroute-secret