apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: test-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  secretName: test-keystore
  dnsNames:
    - test
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: test-selfsigned
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: jks-password
        key: password
  subject:
    countries:
      - US
    localities:
      - A Park
    organizationalUnits:
      - Parks and Recreation
    provinces:
      - FL
