resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.2/cert-manager.yaml
  - testroute.yaml
  - cert.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: testroute-xml
    files:
      - integrationRoute.xml
      # If the file is not named 'integrationRoute.xml', you will have to add a key with that name:
      # - integrationRoute.xml=<path-to-file>
  - name: testroute-props
    files:
      - application.yaml

secretGenerator:
  - name: testroute-secret
    literals:
      - test.secret=pass123
  - name: jks-password
    literals:
      - password=password
