---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: keip-integrationroute-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: keip.octo.com/v1alpha1
    resource: integrationroutes
    revisionHistory:
      # TODO: Does this actually work if only the CM's content changes?
      fieldPaths:
        - spec.routeConfigMap
  childResources:
    - apiVersion: apps/v1
      resource: deployments
      # TODO: Experiment with different update methods
      updateStrategy:
        method: RollingRecreate
        statusChecks:
          conditions:
            - type: Ready
              status: "True"
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: RollingRecreate
        statusChecks:
          conditions:
            - type: Ready
              status: "True"
  hooks:
    sync:
      webhook:
        url: http://integrationroute-webhook.keip/sync
        timeout: 10s
---
apiVersion: v1
kind: Namespace
metadata:
  name: keip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrationroute-webhook
  namespace: keip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrationroute-webhook
  template:
    metadata:
      labels:
        app: integrationroute-webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/octoconsulting/keip/route-webhook:0.13.0
          ports:
            - containerPort: 7080
              name: webhook-http
          env:
            - name: INTEGRATION_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: keip-controller-props
                  key: integration-image
            - name: LOG_LEVEL
              value: INFO
          resources:
            requests:
              cpu: "100m"
            limits:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: integrationroute-webhook
  namespace: keip
spec:
  selector:
    app: integrationroute-webhook
  ports:
    - port: 80
      targetPort: webhook-http
