---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: integrationroute-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: keip.connexta.com/v1alpha1
    resource: integrationroutes
    revisionHistory:
      # TODO: Does this actually work if only the CM's content changes?
      fieldPaths:
        - spec.routeConfigMap
  childResources:
    - apiVersion: apps/v1
      resource: deployments
      # TODO: Experiment with different update methods
      updateStrategy:
        method: RollingRecreate
        statusChecks:
          conditions:
            - type: Ready
              status: "True"
  hooks:
    sync:
      webhook:
        # TODO: Figure out how to avoid having to update when ns changes
        url: http://integrationroute-webhook.default/sync
        timeout: 10s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrationroute-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrationroute-webhook
  template:
    metadata:
      labels:
        app: integrationroute-webhook
    spec:
      containers:
        - name: webhook
          image: python:3.11.4-slim
          command: ["python", "/hooks/sync.py"]
          volumeMounts:
            - name: hooks
              mountPath: /hooks
          env:
            - name: INTEGRATION_IMAGE
              value: keip-integration:0.0.1-SNAPSHOT
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: hooks
          configMap:
            name: integrationroute-sync-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: integrationroute-webhook
spec:
  selector:
    app: integrationroute-webhook
  ports:
    - port: 80
      targetPort: 80
