apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: integrationroutes.keip.octo.com
spec:
  group: keip.octo.com
  names:
    kind: IntegrationRoute
    plural: integrationroutes
    singular: integrationroute
    shortNames:
      - ir
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                annotations:
                  description: "Annotations to add to the IntegrationRoute pod and deployment templates"
                  type: object
                  additionalProperties:
                    type: string
                labels:
                  description: "Labels to add to the IntegrationRoute pod and deployment templates"
                  type: object
                  additionalProperties:
                    type: string
                routeConfigMap:
                  description: "Name of a ConfigMap containing integration route definitions. The ConfigMap should be in the same namespace as the IntegrationRoute resource"
                  type: string
                propSources:
                  description: "List of names or labels referencing ConfigMap sources that will be included as Spring PropertySources. The ConfigMaps should be in the same namespace as the IntegrationRoute resource"
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                    oneOf:
                      - properties:
                        required:
                          - name
                      - properties:
                        required:
                          - labels
                secretSources:
                  description: "List of names referencing Secrets that will be mounted into the integration route container and included as Spring PropertySources. The Secrets should be in the same namespace as the IntegrationRoute resource"
                  type: array
                  items:
                    type: string
                configMaps:
                  description: "List of configMaps that will be mounted into the integration route container"
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                env:
                  description: "List of environment variables to set in the container (cannot be updated)"
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                      - name
                      - value
                envFrom:
                  description: "List of sources to populate environment variables in the container (cannot be updated)"
                  type: array
                  items:
                    type: object
                    properties:
                      configMapRef:
                        type: object
                        properties:
                          name:
                            type: string
                      secretRef:
                        type: object
                        properties:
                          name:
                            type: string
                    oneOf:
                      - properties:
                        required:
                          - configMapRef
                      - properties:
                        required:
                          - secretRef
                replicas: # not yet implemented
                  description: "Number of containers running the integration route"
                  type: integer
                  minimum: 1
                  maximum: 20 # TODO: Figure out a reasonable maximum
                  default: 1
                persistentVolumeClaims:
                  description: "List with the names of PersistentVolumeClaims and their mountPaths on the pod container"
                  type: array
                  items:
                    type: object
                    properties:
                      claimName:
                        type: string
                      mountPath:
                        type: string
                    required:
                      - claimName
                      - mountPath
                tls:
                  description: "Configure server and client TLS connections."
                  type: object
                  properties:
                    truststore:
                      description: "Configure client TLS connections using a JKS or PKCS12 truststore. A JKS truststore should have its password set to 'changeit', while a PKCS12 truststore should have an empty password."
                      type: object
                      properties:
                        configMapName:
                          type: string
                        key:
                          type: string
                        type:
                          type: string
                          enum:
                            - jks
                            - pkcs12
                      required:
                        - configMapName
                        - key
                        - type
                    keystore:
                      description: "Configure HTTP server TLS connections using a JKS or PKCS12 keystore. The keystore password should be stored in a secret and referenced in the route Custom Resource. The format of the secret should be `password=<password>`."
                      type: object
                      properties:
                        secretName:
                          type: string
                        key:
                          type: string
                        type:
                          type: string
                          enum:
                            - jks
                            - pkcs12
                        passwordSecretRef:
                          type: string
                      required:
                        - secretName
                        - key
                        - type
                        - passwordSecretRef
              required:
                - routeConfigMap
          required:
            - spec
      subresources: # Can be used to add status information to CustomResource objects
        status: { }
