resources:
  - testroute.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: testroute-xml
    files:
      - integrationRoute.xml

secretGenerator:
  - name: pkcs12-password
    literals:
      - password=changeit
