apiVersion: keip.octo.com/v1alpha1
kind: IntegrationRoute
metadata:
  name: testroute
  annotations:
    cert-manager.io/alt-names: "cloud-integration-route-actuator.default.svc.cluster.local"
    cert-manager.io/cluster-issuer: "test-selfsigned"
    cert-manager.io/common-name: "testroute"
    cert-manager.io/subject-organizationalunits: "Parks and Recreation"
    cert-manager.io/subject-countries: "US"
    cert-manager.io/subject-provinces: "FL"
    cert-manager.io/subject-localities: "A Park"
spec:
  routeConfigMap: testroute-xml
  # Optional TLS configuration
  tls:
    keystore:
      pkcs12:
        secretName: testroute-certstore
        key: keystore.p12
        passwordSecretRef: pkcs12-password
---
apiVersion: v1
kind: Service
metadata:
  name: testroute
spec:
  selector:
    app.kubernetes.io/instance: integrationroute-testroute
  ports:
    - name: https-port
      port: 8443
      protocol: TCP
      targetPort: 8443